server:
  port: 8080
logging:
  level:
    root: info
spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      additional-paths:
        - static/built/*
  data:
    rest:
      basePath: api
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
