export enum Paths {
    TRANSFORMERS = "/transformers",
    BASES = "/bases",
    UPGRADES = "/upgrades",
    WEAPONS = "/weapons",
    TRANSPORT = "/transport",
    INSPECTIONS = "/inspections",
    OPERATIONS = "/operations",
    BATTLE_FIELDS = "/battleFields",
    ENERGON = "/energon",
    EQUIPMENT = "/equipment",
    INJURY = "/injury",
    MODIFICATIONS = "/modifications",
    POSITIONS = "/positions",
}
